language: python
python: 3.6
install: "pip install Lektor"
script: "lektor build -O web && git checkout -b gh-pages && git add . && git -c user.name=LEKTOR_DEPLOY_USERNAME commit -m init && git push -f -q https://LEKTOR_DEPLOY_USERNAME:LEKTOR_DEPLOY_PASSWORDY@github.com/LEKTOR_DEPLOY_USERNAME/european-pirateparty.eu-gh-pages gh-pages &>/dev/null"
deploy:
  provider: script
  script: "lektor deploy ghpages"
